function [ lbpHistUniform, lbpHistRotInv, lbpHistRotInvAndDiscretizedVar,...
whereHistogramLbpIsComputableWithoutArtifacts,...
tableUniformToNormal_numOf1,...
tableUniformToNormal_debutDes1,...
tableNormalToUniform2,...
lbpRotInv, ...
lbpUniform,...
rangeRotInv,...
rangeUniform] = computeLbpHistogram2( ...
    imageGris, n, R, good, nbBinsToDiscretizeVar, semiSize, ...
    kernelOption, optionForEdges)
% kernelOption :
%     1 : gaussian
%     2 : hanning
%     3 : square
%     4 : disk
% optionForEdges :
%     0 : zero outside, and don't crop at the end
%     1 : zero outside, and crop at the end
%     2 : symmetry outside, and crop at the end.
% [kernelOption, optionForEdges] = deal(2,2);

[ numberOfOnes,...
numberOfTransitions,...
wherePointwiseLbpIsComputableWithoutArtifacts,...
lbpLists, ...
lbp, ...
lbpRotInv, ...
lbpUniform, ...
var1, ...
discretizedVar,...
tableUniformToNormal_numOf1,...
tableUniformToNormal_debutDes1,...
tableNormalToUniform2,...
rangeDiscretizedVar] =...
computeLbpPointwise_informations(imageGris, n, R, good, nbBinsToDiscretizeVar);

rangeRotInv=0:(n+1);
rangeUniform=0:(2 + (n-1)*n);
[Mx,My]=size(imageGris);
fullSize=2*semiSize+1;
shapePatch = ones(fullSize);
whereHistogramLbpIsComputableWithoutArtifacts = ...
    imerode(wherePointwiseLbpIsComputableWithoutArtifacts, shapePatch);

%% lbpRotInv = numberOfOnes
lbpHistRotInv=zeros(Mx,My,length(rangeRotInv));
% sigma = 2*semiSize+1;
for i=rangeRotInv
    lbpHistRotInv(:,:,i+1) = ...
        blur( double(lbpRotInv == i),...
              fullSize, kernelOption, optionForEdges );
end
% lbpHistRotInv = normalizeKnownArea( lbpHistRotInv, good );
% imagesc(lbpHistRotInv(:,:,5));


%% lbpUniform = numberOfOnes x debutDes1
lbpHistUniform=zeros(Mx,My,length(rangeUniform));
for i=rangeUniform
    lbpHistUniform(:,:,i+1) = blur(double(lbpUniform == i), fullSize,...
        kernelOption, optionForEdges);
end
% imagesc(sum(lbpHistUniform,3));
% lbpHistUniform = normalizeKnownArea( lbpHistUniform, good );
% imagesc(lbpHistUniform(:,:,5));


%% RotInvAndDiscretizedVar = numberOfOnes x discretizedVar
% length(rangeRotInv)==n+2
lbpHistRotInvAndDiscretizedVar=zeros(Mx,My,(n+2)*nbBinsToDiscretizeVar);
rangeDiscretizedVar=0:(nbBinsToDiscretizeVar-1);
% i_nb=length(rangeRotInv); % = n+2
% j_nb=length(rangeDiscretizedVar); % = nbBinsToDiscretizeVar
for i=rangeRotInv
    for j=rangeDiscretizedVar
        lbpHistRotInvAndDiscretizedVar(:,:,i+(j*(n+2))+1) = ...
            blur(double((lbpRotInv == i) & (discretizedVar==j)), fullSize,...
            kernelOption, optionForEdges);
    end
end
% imagesc(sum(lbpHistRotInvAndDiscretizedVar,3));
% lbpHistRotInvAndDiscretizedVar = normalizeKnownArea(...
%  lbpHistRotInvAndDiscretizedVar, good );
% imagesc(lbpHistRotInvAndDiscretizedVar(:,:,6))





