
nameFolderInput = '../../../Input/ImagesInput_GepshteinAndKeller';
nameFileInput_1='rice.bmp';
nameFolderOutputRoot = '../../../Output/GepshteinAndKeller';

% @functionToGetDescriptor_LbpRotInv
% @functionToGetDescriptor_LbpRotInvAndVar
% @functionToGetDescriptor_LbpUniform
% @functionToGetDescriptor_Wexler
% @functionToGetDescriptor_Windowing

% @functionToGetDistances_Euclidian
% @functionToGetDistances_Euclidian_patch
% @functionToGetDistances_Hellinger
% @functionToGetDistances_Shannon

% [nameFolder,nameFile,sizeImage,
% sigma_tenseur,sigma_gradient,R,n,sigma,nbBinsToDiscretizeVar,...
% functionToGetDescriptor,...
% functionToGetDistances,...
% kForKnn,alpha,markovOrSym,...
% numberOfEigenvectorsToKeep,t,...
% nameFolderOutputRoot,nameFileOfExperiment_suffix]...
% =deal(params{:});

paramsAll={...
{nameFolderInput,nameFileInput_1, 200,...
0.8,0, 1,8, 1.2,5,...
@functionToGetDescriptor_Wexler,...
@functionToGetDistances_Euclidian,...
30,0,1,10,1,...
nameFolderOutputRoot,'Rice-200-Wexler'}...
...
{nameFolderInput,nameFileInput_1, 200,...
0.8,0, 1,8, 1.2,5,...
@functionToGetDescriptor_Windowing,...
@functionToGetDistances_Euclidian_patch,...
30,0,1,10,1,nameFolderOutputRoot,'Rice-200-Windowing'}...
...
{nameFolderInput,nameFileInput_1, 200,...
0.8,0, 1,8, 1.2,5,...
@functionToGetDescriptor_LbpRotInv,...
@functionToGetDistances_Euclidian,...
30,0,1,10,1,nameFolderOutputRoot,'Rice-200-LbpRotInv-1-8-1.2-Euclidian'}...
...
{nameFolderInput,nameFileInput_1, 200,...
0.8,0, 2,16, 1.2,5,...
@functionToGetDescriptor_LbpRotInv,...
@functionToGetDistances_Euclidian,...
30,0,1,10,1,nameFolderOutputRoot,'Rice-200-LbpRotInv-2-16-1.2-Euclidian'}...
...
{nameFolderInput,nameFileInput_1, 200,...
0.8,0, 3,24, 1.2,5,...
@functionToGetDescriptor_LbpRotInv,...
@functionToGetDistances_Euclidian,...
30,0,1,10,1,nameFolderOutputRoot,'Rice-200-LbpRotInv-3-24-1.2-Euclidian'}...
...
{nameFolderInput,nameFileInput_1, 200,...
0.8,0, 1,8, 1.2,5,...
@functionToGetDescriptor_LbpRotInvAndVar,...
@functionToGetDistances_Euclidian,...
30,0,1,10,1,nameFolderOutputRoot,'Rice-200-LbpRotInvAndVar-1-8-5-1.2-Euclidian'}...
...
{nameFolderInput,nameFileInput_1, 200,...
0.8,0, 1,8, 1.2,5,...
@functionToGetDescriptor_LbpUniform,...
@functionToGetDistances_Euclidian,...
30,0,1,10,1,nameFolderOutputRoot,'Rice-200-LbpUniform-1-8-1.2-Euclidian'}...
};


for i=6:7 %1:length(paramsAll)
    params=paramsAll{i};
    
    [diffusionMapsCoordinates_images,...
    eigenvalues]=...
    testOfParams( params );

    seeOldExperiment(eigenvalues,diffusionMapsCoordinates_images)
end











