function [x,...
y,...
d]=...
	functionToGetDistances_Shannon(...
textureDescriptor,...
whereTextureDescriptorIsDefined,...
kForKnn)


[x,y,d]=...
	generalizedPatchMatch_Shannon...
(textureDescriptor,...
textureDescriptor,...
5,...
kForKnn,...
whereTextureDescriptorIsDefined,...
whereTextureDescriptorIsDefined);

x=x+1;
y=y+1;

