function [x,...
y,...
d]=...
	functionToGetDistances_Euclidian_patch(...
textureDescriptor,...
whereTextureDescriptorIsDefined,...
kForKnn)

%%%%%%%%%%%%%%%%%%%%%%%
diameter=11;
mask=getSmoothingKernel(2, diameter);

widthAddedAround=(diameter-1)/2;
textureElargie= ...
   extendImageByConst( ...
     textureDescriptor, widthAddedAround , 0 );

whereTextureDescriptorIsDefinedElargie=...
    extendImageByConst( ...
        whereTextureDescriptorIsDefined, widthAddedAround , 0 );

whereTextureDescriptorFullyKnownElargie=...
    imerode(whereTextureDescriptorIsDefinedElargie,...
		ones(diameter));


%%%%%%%%%%%%%%%%%%%
[x,y,d]=...
	generalizedPatchMatch_EuclidianSquared_patch...
(textureElargie,...
textureElargie,...
5,...
kForKnn,...
mask,...
whereTextureDescriptorIsDefinedElargie,...
whereTextureDescriptorIsDefinedElargie,...
whereTextureDescriptorFullyKnownElargie);

d=sqrt(d);
x=x+1;
y=y+1;







