function [x,...
y,...
d]=...
	functionToGetDistances_Euclidian(...
textureDescriptor,...
whereTextureDescriptorIsDefined,...
kForKnn)


[x,y,d]=...
	generalizedPatchMatch_EuclidianSquared...
(textureDescriptor,...
textureDescriptor,...
5,...
kForKnn,...
whereTextureDescriptorIsDefined,...
whereTextureDescriptorIsDefined);

x=x+1;
y=y+1;
d=sqrt(d);

