function answer = proba( lambda, energies_1, energies_2, T, i )
%i=1:104;
answer = ...
    lambda/...
        (lambda + ...
            exp(...
                    (- energies_1(i) - sum(energies_2(i,:))) / T...
                )...
        );
end

