
listeIncludes = {...
    '.',...
    '../1) toolboxDivers', ...
    '../1) toolboxFiniteDifferences', ...
    '../../Code made by other people'};
for i=1:length(listeIncludes)
    includeRelativePath( listeIncludes{i} );
end



