function sparseCorrelationMatrix=...
	functionToGetTheCorrelationMatrix(...
I,J,D,N,...
indexOfVoisins,numberOfVoisins,...
distanceOfVoisins)

%%
% sparseCorrelationMatrix=...
% 	functionToGetTheCorrelationMatrix_median(...
% I,J,D,N);

% functionToGetTheCorrelationMatrix_maxSurTrois
% functionToGetTheCorrelationMatrix_maxSurTroisAndMedian
% functionToGetTheCorrelationMatrix_median

%%
sparseCorrelationMatrix=...
	functionToGetTheCorrelationMatrix_bertozzi(...
I,J,D,N,...
indexOfVoisins,numberOfVoisins,...
distanceOfVoisins);



