function [ anglesApprox, canBeLifted ] = calculThings(...
sigma_gradient, sigma_tenseur,...
coeffThreshGrad, coeffThreshAnisotropy)

% These variables should have been declared before, and set global before
% also.
% global imageInReconstr good thetaNumber;
global image0  thetaNumber imageInReconstr good;

order=2;
displayThings=false;

if(sum(good)==numel(good))
    [ ~, ~, ~, ~, ~,...
    normeOfGrad, anisotropy, ~,...
    ~, anglesApprox] = ...
        getAngles(image0, ones(size(image0)), sigma_tenseur,...
        sigma_gradient, thetaNumber, order, displayThings);
else
    [ ~, ~, ~, ~, ~,...
    normeOfGrad, anisotropy, ~,...
    ~, anglesApprox] = ...
        getAngles(imageInReconstr, good, sigma_tenseur,...
        sigma_gradient, thetaNumber, order, displayThings);
end
% imageInReconstr, good,
% image0, ones(size(image0)),

canBeLifted=(normeOfGrad>=coeffThreshGrad) &...
    (anisotropy >= coeffThreshAnisotropy);

end

