function [S,k2] = calculThings4( sigma_tenseur, sigma_gradient, k )
global image0  thetaNumber;%imageInReconstr good
order=2;
displayThings=false;
[ S,  ~,  ~,  ~,  ~,...
 ~,  ~,  ~,...
 ~, ~] = ...
getAngles(image0,  ones(size(image0)), sigma_tenseur,...
  sigma_gradient, thetaNumber, order, displayThings);
k2=round(k);
