function normeOfGrad = getGradient( sigma_gradient, sigma_tenseur )
% global imageInReconstr good thetaNumber;
global image0 thetaNumber;%imageInReconstr good

order=2;
displayThings=false;
% [ S, lambda1, lambda2, e1, e2,...
%     normeOfGrad, anisotropy, anisotropyLog,...
%     anglesExacts, anglesApprox] = ...
[ ~, ~, ~, ~, ~,...
    normeOfGrad, ~, ~,...
    ~, ~] = ...
getAngles(image0, ones(size(image0)), sigma_tenseur,...
sigma_gradient, thetaNumber, order, displayThings);
% getAngles(imageInReconstr, good, sigma_tenseur,...
%     sigma_gradient, thetaNumber, order, displayThings);

end

