function [...
textureDescriptor,...
whereTextureDescriptorIsDefined]=...
	functionToGetDescriptor_LbpUniform(...
image3d,...
good,...
paramsToGetDescriptor)


n=paramsToGetDescriptor.n;
R=paramsToGetDescriptor.R;
sigma=paramsToGetDescriptor.sigma;

imageGris=rgb2gray(image3d);

[lbpUniform_pointwise, ...
lbpUniform_Hist,...
wherePointwiseLbpIsComputableWithoutArtifacts,...
whereHistogramLbpIsComputableWithoutArtifacts,...
rangePointwise]=...
lbpUniform(imageGris, good, n, R, sigma);

textureDescriptor=lbpUniform_Hist;
whereTextureDescriptorIsDefined=...
	whereHistogramLbpIsComputableWithoutArtifacts;


	
	