function [...
textureDescriptor,...
whereTextureDescriptorIsDefined]=...
	functionToGetDescriptor_Wexler(...
image3d,...
good,...
paramsToGetDescriptor)

sigma_tenseur=paramsToGetDescriptor.sigma_tenseur;
sigma_gradient=paramsToGetDescriptor.sigma_gradient;

imageGris=rgb2gray(image3d);

[dx, dy] = ...
  gradPerso3(imageGris, good, sigma_tenseur,...
  sigma_gradient);

textureDescriptor=cat(3, image3d, dx, dy);
whereTextureDescriptorIsDefined=good;

	
	