function [...
textureDescriptor,...
whereTextureDescriptorIsDefined]=...
	functionToGetDescriptor_Windowing(...
image3d,...
good,...
paramsToGetDescriptor)

textureDescriptor=image3d;
whereTextureDescriptorIsDefined=good;




	
	