function [...
textureDescriptor,...
whereTextureDescriptorIsDefined]=...
	functionToGetDescriptor_LbpRotInv(...
image3d,...
good,...
paramsToGetDescriptor)

n=paramsToGetDescriptor.n;
R=paramsToGetDescriptor.R;
sigma=paramsToGetDescriptor.sigma;

imageGris=rgb2gray(image3d);

[lbpRotInv_pointwise, ...
lbpRotInv_Hist,...
wherePointwiseLbpIsComputableWithoutArtifacts,...
whereHistogramLbpIsComputableWithoutArtifacts,...
rangePointwise]=...
lbpRotInv(imageGris, good, n, R, sigma);

textureDescriptor=lbpRotInv_Hist;
whereTextureDescriptorIsDefined=...
	whereHistogramLbpIsComputableWithoutArtifacts;






	
	