function images=convertListToImage(...
	vectors,... % each column is a vector
	indexToX,...
	indexToY,...
	Mx,...
	My)

Mz=size(vectors,2);
images=zeros(Mx,My,Mz);
for i=1:size(vectors,1)
	images(indexToX(i),indexToY(i),:)=...
		reshape(vectors(i,:),[1 1 Mz]);
end

