function [...
... %leftEigenVectors,...
rightEigenVectors, ...
eigenvalues]=...
	functionToDoTheEigenDecomposition(...
normalizedSparseCorrelationMatrix, ...
numberOfEigenvectorsToKeep,...
markovOrSym)

% eigopt.tol=3*1e-8; %default 1e-10
% eigopt.maxit=200; %default 300
% 
% [leftEigenVectors,...
% eigenvalues,...
% rightEigenVectors] =...
% 	svds(...
% normalizedSparseCorrelationMatrix,...
% numberOfEigenvectorsToKeep,...
% 'L', eigopt);

% eigopt.tol=1e-12; %default eps=2.2204e-16
% eigopt.maxit=200; %default 300
if ~markovOrSym
    eigopt.issym=1;
end

if(exist('eigopt'))
    [rightEigenVectors,eigenvalues]=...
        eigs(normalizedSparseCorrelationMatrix,...
        numberOfEigenvectorsToKeep,...
        'lm',...
        eigopt);

%     [leftEigenVectors,~]=...
%         eigs(normalizedSparseCorrelationMatrix',...
%         numberOfEigenvectorsToKeep,...
%         'lm',...
%         eigopt);
else
    [rightEigenVectors,eigenvalues]=...
        eigs(normalizedSparseCorrelationMatrix,...
        numberOfEigenvectorsToKeep);

%     [leftEigenVectors,~]=...
%         eigs(normalizedSparseCorrelationMatrix',...
%         numberOfEigenvectorsToKeep);
end

eigenvalues=diag(eigenvalues);
%[~,ind] = sort(abs(eigenvalues),'descend');
[~,ind] = sort(eigenvalues,'descend');
% leftEigenVectors=leftEigenVectors(:,ind);
rightEigenVectors=rightEigenVectors(:,ind);
eigenvalues=eigenvalues(ind);







